### ISSUE TITLE
"Hello world" fails to compile

### ISSUE THREAD

**Issue by IngwiePhoenix** [shift-js/shift-js#300]
I just wanted to try this out and see what happens. Well, this happened:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/T/swift $ cat hello.swift 
// Hello, World! Program
import Swift
print("Hello, World!")
Ingwie@Ingwies-Macbook-Pro.local ~/W/T/swift $ swiftc hello.swift -o hello
Ingwie@Ingwies-Macbook-Pro.local ~/W/T/swift $ ./hello
Hello, World!
Ingwie@Ingwies-Macbook-Pro.local ~/W/T/swift $ shift.js hello.swift
Unhandled rejection TypeError: v.error is not a function
    at statement (/usr/local/lib/node_modules/shift.js/transpiler/parser/statement.js:74:7)
    at statements (/usr/local/lib/node_modules/shift.js/transpiler/parser/statements.js:23:9)
    at parseTokenStream (/usr/local/lib/node_modules/shift.js/transpiler/parser/parser.js:102:13)
    at Object.compile (/usr/local/lib/node_modules/shift.js/transpiler/api.js:23:22)
    at /usr/local/lib/node_modules/shift.js/command.js:66:35
    at tryCatcher (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (timers.js:637:19)
```

Anything I can do to fix this?

**Comment by MichaelNeas** [comment]
@IngwiePhoenix I encountered the same problem as you and received the same stack track.

To add to this, `sudo npm install --g shift.js` returns a bunch of errors running node 10.15.3 and npm version.

Also upon building the project locally a ton of dependencies are depreciated and when I tried to resolve some errors I found there are also problems in a dependency https://github.com/estools/escodegen

Seems to me that this project is pretty dead, and has been dead for 4 years unfortunately 😢

**Comment by therealjuanmartinez** [comment]
Same/similar issue: 

```
Unhandled rejection SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.checkForLiteral (/usr/local/lib/node_modules/shift.js/transpiler/lexer/lexerFunctions.js:79:20)
    at module.exports (/usr/local/lib/node_modules/shift.js/transpiler/lexer/lexer.js:257:24)
    at Object.compile (/usr/local/lib/node_modules/shift.js/transpiler/api.js:23:29)
    at /usr/local/lib/node_modules/shift.js/command.js:66:35
    at tryCatcher (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/shift.js/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
